# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: false
  branches:
    include:
    - desevolvimento


pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  fetchDepth: 1
  clean: true
  fetchTags: false

- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    mkdir -p '$(Build.BinariesDirectory)/notebooks'
  displayName: 'Run a multi-line script'
